# .github/workflows/main.yml

name: Run Python Tests

# Run this workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    # Use the latest version of Ubuntu on a GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code so the job can access it
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up a specific version of Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: (Optional) Install dependencies if you have them
      # This example has no dependencies, but in a real project you would
      # uncomment the following lines.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the tests using the unittest module
      - name: Run tests
        run: python -m unittest discover